### ISSUE TITLE
Start an IDE instead of a shell

### ISSUE THREAD

**Issue by yozhgoor** [yozhgoor/cargo-temp#15]
@YohDeadfall make the point that some users use an IDE instead of a terminal for handle their Rust project's workflow.

This issue will investigate some solutions to make that possible across all platforms already available.

**Comment by YohDeadfall** [comment]
It depends on IDE and happens with VS Code which is Electron based, so things are not easy, yes. But there's the magical `--wait` argument which keeps the process running till windows is closed. Therefore, mine proposal is to have `editor` and `editor_args` settings in the config to customize the behavior.

As an MVP it's a good starting point, and if there's another IDE which has no such an attribute and opens a new window, then we can think about adding another option to keep the tool running.

```toml
editor = "path to editor"
editor_args = [ "list", "of", "arguments" ]
```

Arguments should be passed after the path to a temporary folder. At some point we might decide ability to customize that too by a having a placeholder argument, but for this one it would be nice to see a precedence first and do a research on how other applications handle it, especially IDEs consuming `launchSettings.json`.

**Comment by YohDeadfall** [comment]
Huh, the `--wait` option works for files only and not for directories. Closing a tab for the specified file terminates the awaited process.

**Comment by YohDeadfall** [comment]
@cecton, I managed it to work without opening a file. The documentation says that `--new-window` is by default, but looks like it's a lie or half truth. If that argument is explicitly specified passing a directory path works like a charm.
