### ISSUE TITLE
Error: No such file or directory (os error 2) at path "/Users/teymour/.cache/cargo-temp/tmp-woaKxr"

### ISSUE THREAD

**Issue by teymour-aldridge** [yozhgoor/cargo-temp#60]
I ran into this error when trying to create a new project. However, when I created the directory `.cache` it worked fine, so I think the solution is to create it if it does not already exist.

```
teymour@Teymours-Air ~ % cargo temp
Error: No such file or directory (os error 2) at path "/Users/teymour/.cache/cargo-temp/tmp-woaKxr"
teymour@Teymours-Air ~ % mkdir /Users/teymour/.cache 
teymour@Teymours-Air ~ % cargo temp
     Created binary (application) package
teymour@Teymours-Air tmp-6yAwjc % 
```

**Comment by yozhgoor** [comment]
`~/.cache` is the default when using [xdg::BaseDirectories](https://docs.rs/xdg/2.4.1/xdg/struct.BaseDirectories.html#method.new). 
It seems that the default cache folder on MacOs is `~/Library/Caches`.

As a workaround, you can change this path in `~/.config/cargo-temp/config.toml` i suppose:
```toml
temporary_project_dir = "~/Library/Caches/cargo-temp"
```
