### ISSUE TITLE
Request: append name of the project to the directory name

### ISSUE THREAD

**Issue by amanjeev** [yozhgoor/cargo-temp#62]
Thank you for this amazing project that helps me a lot.  I will try to attempt this myself as a feature PR but creating this issue here just for the sake of documentation (also in case I missed something). 

## Current state

Right now I can generate a new temp crate with a specific name by passing `--name` flag like 

```
$ cargo temp --name mytrialproj
```
It generates a directory in the cargo temp directory correctly with name like `tmp-EUsdfsl`. 

## Feature request

If name is specified with `--name` flag, append that to the directory name of the newly generated project. e.g. `tmp-EUsdfsl-mytrialproj`.

**Comment by yozhgoor** [comment]
Hello there, thanks for the issue.
You can definitely do that when you create the [`tmp_dir`](https://github.com/yozhgoor/cargo-temp/blob/868b717a768f34a0931a563d19d57479751bd0f5/src/run.rs#L45) via the [`Builder`](https://docs.rs/tempfile/latest/tempfile/struct.Builder.html#method.suffix).
Let me know if you need me to take a look.

I'm really glad you like the project :crab:

**Comment by yozhgoor** [comment]
As you can see I gave it a shot on #69.
Starting by using the project name as the suffix of the project name.
The goal here is to easily rename a temporary directory from `tmp-wXyZ-project` to `project`, am I right?
So I added that behavior directly so you don't have to do it by hand but now I think that it would be better to keep the renaming without using the suffix.

So your project will still be `tmp-wXyZ` but if you decide to preserve it, it will be renamed using the provided project name. any thoughts?

**Comment by amanjeev** [comment]
>  The goal here is to easily rename a temporary directory from tmp-wXyZ-project to project, am I right?

I do not think the current command when passed `--name` even appends the `-project`. 

I am not sure if I want it to be renamed to just `project`.  I could foresee some directory names issues etc.?  I would still keep the directory `tmp-wXyZ-` prefix but add the `-project`.  I am asking for this just to identify by looking in the temp directory what the particular project was created for.

This is why I think that we can even create projects with `-project` appended to the directory name if `--name` is passed while creation.  Whether or not the project is to be kept or deleted.

Sorry for the confusion. What do you think of the above?

**Comment by yozhgoor** [comment]
No problem, It was the subject of the request and I can revert without problems.
I only though you wanted this for an easier renaming when preserving the temporary project.

So you are not for the renaming of the temporary project if you provide a project name and want to preserve it?
@cecton what do you think about this?

**Comment by yozhgoor** [comment]
now we do both:
```bash
Temporary project created at: /home/yozhgoor/.cache/cargo-temp/tmp-Qw57q8-happy-dog
# delete the `TO_DELETE` file and exit the shell.
Project directory preserved at: /home/yozhgoor/.cache/cargo-temp/happy-dog
```

**Comment by cecton** [comment]
I think we have multiple features here being discussed.

1.  OP asked that the name of the project is appended to the temporary directory name. The idea is to identify the project more easily if you list all the projects.

    Although this does not make sense when the directory is in the cache or in a temporary location, it does make sense if you use your own "repos" directory (where you put all your projects).

2.  You did propose another feature that would rename the project's directory to the name of the project if the project is preserved.

    It's not the feature requested but I can see the value in this because if you want to preserve the directory, you will want to give it a nice name.

So I think..... why_not_both.gif

Even if you rename the project, it's still useful to be able to see which temporary project is which because the user might want to create multiple temporary projects at the same time.

In the same trend, I could see a use of adding another feature that would move the project to a different location if the project is preserved. (3)

In order to make OP happy though I would start by feature 1 and do a quick release for that already. (Because it's trivial to implement). Feature 2 and 3 can come later.

**Comment by yozhgoor** [comment]
> In order to make OP happy though I would start by feature 1 and do a quick release for that already. (Because it's trivial to implement). Feature 2 and 3 can come later.

Note that 1 and 2 are already implemented in  #69.
I added an issue for 3 (#71).

**Comment by amanjeev** [comment]
Thank you @cecton and @yozhgoor ! The OP is happy already. :smile:

**Comment by cecton** [comment]
![you-ll-be-silent-gif](https://c.tenor.com/dBk7hP8jg2YAAAAC/bortus-orville.gif)
