### ISSUE TITLE
Move the project to a different location if the project is preserved.

### ISSUE THREAD

**Issue by yozhgoor** [yozhgoor/cargo-temp#71]
As mentioned in #62, I would be great to move the project to a different location if the project is preserved.

**Comment by era** [comment]
@yozhgoor if this is still open for grabs I would like to give it a chance :), the idea is to move the entire dir to another location with a new command right? something like `cargo temp mv new_location`? 

Also, I'm probably missing something, what is the difference between just running an `mv temp-123 /projects/my_cool_project` and this?

**Comment by yozhgoor** [comment]
Hey, cool!
The idea is to allow the user to move the temporary project to a new location if they want to preserve it.

We currently create the temporary project at the location given by the `temporary_project_dir` setting in the config file but most people use a location like `~/repos` so it would be handy to be able to move a project you want to preserve directly in that location.

I was thinking about adding a `preserved_project_dir` setting in the config file at first but we can maybe use a flag like `cargo temp --move <new_location>` (or both).

**Comment by yozhgoor** [comment]
You can use `mv temp-123 /projects/my_new_project` too but if you type `cargo-temp` from `~`, you create a temporary project at `~/.cache/cargo-temp/tmp-123` and when you exit the shell you go back to `~`, so you have to manually search for `tmp-123` by yourself.

**Comment by yozhgoor** [comment]
For me we have three use-case for this, you have a project and you want to preserve it so:
* you don't care and you leave the project at the `temporary_project_dir` location (so the `preserved_project_dir` is `None`)
* you don't know if you are going to preserve the project but you have set the `preserved_project_dir` to move the project to `new_location`.
* there is a chance that you are going to preserve the project and you don't have set the `preserved_project_dir` setting in your config file or you want to choose another location that the one given by `preserved_project_dir`. so you use the `cargo-temp --move <new_location>` command.

Note that the naming can change if you want, you do you!

**Comment by YohDeadfall** [comment]
The best option here in my opinion is to prompt the user when the shell is terminated and have a flag with a config option controlling that behavior. In addition to that you have to check that the `cargo-temp` is running in the interactive mode before prompting the user. That part can be done using `isatty` function. If it returns `false` then the checking file descriptor is redirected/piped.

**Comment by yozhgoor** [comment]
I'm not really sure about this one @YohDeadfall, that's maybe a bit too verbose for a tool like cargo-temp, most people use cargo-temp to create little project, on the fly and that can be huge to refactor since we need to adapt the `prompt` system from the config file and the purpose is not really the same (and it's already kinda verbose tbh).

This can be more "automagic" if you handle this feature by playing with the config file. It's more fun for the developer and easier for the user.

**Comment by cecton** [comment]
(I'm not bringing my point of view here, only helping with the communication... hopefully)

> @yozhgoor if this is still open for grabs I would like to give it a chance :), the idea is to move the entire dir to another location with a new command right? something like `cargo-temp mv new_location`?

I don't think that was the idea @yozhgoor had.

@yozhgoor correct me if I'm wrong but what you want is more something like this:

1. User starts cargo-temp normally
2. User deletes TO_DELETE file in order to tell cargo-temp "please do not this project when I exit the sell"
3. User exits the shell
4. Normally the directory is preserved where it was created (in `~/.cache/cargo-temp/tmp-xyz`). This nice but it's also annoying because it's remote in the user's home directory hierarchy. So @yozhgoor would like to have a setting in the config file of cargo-temp that gives a "target" directory. When the project needs to be preserved, instead of staying in `~/.cache/cargo-temp`, it would go to that directory.


> since we need to adapt the `prompt` system from the config file

Pretty sure that's not what @YohDeadfall meant.

A prompt is an invitation on screen for the user to provide input. I know the "prompt" is also the shell's prompt but I doubt very much @YohDeadfall was talking about that prompt :joy: 

> In addition to that you have to check that the `cargo-temp` is running in the interactive mode before prompting the user.

cargo-temp is always running in interactive.... wait... ah yes maybe on Windows it's not xD Ok I see, it's the "editor" parameter of cargo-temp

**Comment by YohDeadfall** [comment]
It's interactive even on Windows if it's executed by the user. It's just for those who will use `cargo-temp` with redirected input, but honestly, I have no idea who that people are.

**Comment by cecton** [comment]
`cargo temp <<< "Hello World"` ?

I doubt that this is a valid use case

**Comment by yozhgoor** [comment]
> correct me if I'm wrong but what you want is more something like this:

That's right but @era got a point somehow so why_not_both.gif 

> A prompt is an invitation on screen for the user to provide input. I know the "prompt" is also the shell's prompt 

I understood that @YohDeadfall talk about a way to ask where the user want to preserve the directory like we do to ask the user if they really want to delete the config file so we need to modify the `prompt` setting we already have in the config file 
Also correct me if I'm wrong but the interactive mode is a `bool` in the config file that allow the user to choose if they use the prompt or not ?

**Comment by YohDeadfall** [comment]
> Also correct me if I'm wrong but the interactive mode is a bool in the config file that allow the user to choose if they use the prompt or not ?

It depends on the application. Some of them detect it by checking standard IO for redirection, others tend to have a command line flag, and the rest simply ignore existence of non-interactive mode.

**Comment by era** [comment]
What if we start with your initial idea @yozhgoor ? Something as @cecton described:
> 1. User starts cargo-temp normally
>  1. User deletes TO_DELETE file in order to tell cargo-temp "please do not this project when I exit the sell"
> 1. User exits the shell
> 1. Normally the directory is preserved where it was created (in ~/.cache/cargo-temp/tmp-xyz). This nice but it's also annoying because it's remote in the user's home directory hierarchy. So @yozhgoor would like to have a setting in the config file of cargo-temp that gives a "target" directory. When the project needs to be preserved, instead of staying in ~/.cache/cargo-temp, it would go to that directory.

With that in hand, it should be easy to implement the prompt as @YohDeadfall suggested if prompt = true (https://github.com/yozhgoor/cargo-temp/blob/main/src/run.rs#L288) and having the possibility to run a command to move the project.

What do you all think?

**Comment by yozhgoor** [comment]
Sounds good to me

Don't hesitate to ping me if you need!
