### ISSUE TITLE
Solution for what

### ISSUE THREAD

**Issue by stappersg** [yozhgoor/cargo-temp#90]
Please document which problem `cargo-temp` solves.

Longer version:
* What does `cargo-temp` do?
* What does it better as `cargo-generate`?

**Comment by YohDeadfall** [comment]
The first paragraph of the readme states what's the difference and the purpose of that project, but maybe not so clear. So, it aims in making scratches like you would usually do at the Rust playground, but completely on your local machine.  Before the process ends (which can happen when one closes an IDE as an example) it prunes anything the user has done.

In short, it's `mkdir temp_dir;$EDITOR temp_dir;rm -r temp_dir` on steroids.

**Comment by yozhgoor** [comment]
Thanks @YohDeadfall 
The purpose of `cargo-temp` is briefly explained in the README, it helps you to create temporary project with given dependencies that will be deleted when you exit the shell created for this project.
About `cargo-generate`, it is not the same thing: `cargo-generate` create non-temporary Rust project from a template. If you use the `generate` feature of `cargo-temp` is basically the same but the created project is temporary and will be deleted like any other project generated by `cargo-temp`. So `cargo-temp` use `cargo-generate` but don't do anything "better".
